# Generated by Django 3.2 on 2022-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='date',
            new_name='update',
        ),
        migrations.AddField(
            model_name='notes',
            name='creat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
